version: '3.8'
services:
  api: # This is your backend
    build: ./backend
    ports:
      - "5000:3000" # Maps your computer's 5000 to Docker's 3000
    volumes:
      - ./backend:/app
      - /app/node_modules # Prevents local modules from overwriting container modules
    depends_on: 
      - db

  client: # This is your frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true # Keeps the React terminal open
    depends_on:
      - api # Ensures backend starts before frontend

  db: 
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: baladi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes: 
  postgres_data: